name: Build & Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Download from Github and Build C# Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
     #- name: Run tests
     #   uses: game-ci/unity-test-runner@v2
     #   env:
     #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
     #   with:
     #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Build
      - name: Build and Transpile to Javascript for WebGL Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - name: Push WebGL Build to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: webgl
          ITCH_GAME: untitled-game-01
          ITCH_USER: citizendevelopers
          PACKAGE: build
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Chirp Discord Build Channel
        uses: satak/webrequest-action@master
        with:
          url: https://discord.com/api/webhooks/957785581411254272/agK5qWeU1jjOwmNs63ilT57iaESsre7KgE6mlRNaTeej6ImfXs3rNkawUNpqsr5ce_QZ/messages/957827084439396422
          method: PATCH
          payload: '{"content": ":spider_web: **WEBGL BUILD**\nLast update: ${{ steps.date.outputs.date }}\n\nLatest internal version on Itch at https://citizendevelopers.itch.io/untitled-game-01\n\n-"}'
      
      - name: Chirp Discord, Specific Thread
        uses: satak/webrequest-action@master
        with:
          url: https://discord.com/api/webhooks/957785581411254272/agK5qWeU1jjOwmNs63ilT57iaESsre7KgE6mlRNaTeej6ImfXs3rNkawUNpqsr5ce_QZ?thread_id=957830908470231071
          method: POST
          payload: '{"content": "`${{ github.event.commits[0].author.username }}` created `main` branch commit\n${{ github.event.commits[0].url }}\n\n*updating on webgl build now*"}'