name: Build & Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Download from Github and Build C# Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

    # Notification 1
      - name: Discord Notify Start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1183465356099080316/YwzEopsgWpM1FVcEWwTJ-Cvc9AhXOCRwtuEihuqox1VhcOuZ8KvlMXuItviIulaEOC92
          content: ":wrench: **Building WebGL Commit** A new WebGL build started on `main` branch for the `one-more-floor` project. I'll let you know how it goes!"

      - name: Build and Transpile to WebGL
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL

      - name: Fail Notification
        if: ${{ failure() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1183465356099080316/YwzEopsgWpM1FVcEWwTJ-Cvc9AhXOCRwtuEihuqox1VhcOuZ8KvlMXuItviIulaEOC92
          content: ":x: **WebGL build failed** Failed. hmmm. Maybe some god forsaken circles got in there and messed everything up."

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      - name: Push WebGL Build to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: webgl
          ITCH_GAME: one-more-floor
          ITCH_USER: citizendevelopers
          PACKAGE: build
      # Notification 2
      - name: Discord Notify Complete
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: https://discord.com/api/webhooks/1183465356099080316/YwzEopsgWpM1FVcEWwTJ-Cvc9AhXOCRwtuEihuqox1VhcOuZ8KvlMXuItviIulaEOC92
          content: ":white_check_mark: **WebGL build complete** a new build is available at https://citizendevelopers.itch.io/one-more-floor"